apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  annotations:
    # Numero de revisiones
    deployment.kubernetes.io/revisions: "1"
  labels: # Esto es para agregarlo en un grupo
    micro: auth
spec:
  selector:
    matchLabels:
      micro: auth
  replicas: 2 # Numero de replicas
  # Investigar algunas otras propiedades
  #strategy:
  #rollingUpdate:
  # revisionHistoryLimit: 10
  template: # Defección del pod
    metadata:
      name: auth
      labels: # Debe tener el mismo nombre que labels de deployment
        micro: auth
    spec:
      containers:
        - name: auth
          image: auth-micro/v1.0
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "5000"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 25
            timeoutSeconds: 5 # No durar la prueba mas de un segundo
            periodSeconds: 20 # El periodo de tiempo
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 25
            timeoutSeconds: 5 # No durar la prueba mas de un segundo
            periodSeconds: 20 # El periodo de tiempo
            failureThreshold: 3
