apiVersion: v1
kind: Pod
metadata:
  name: auth
spec:
  containers:
    - name: auth
      image: auth-micro
      imagePullPolicy: Never
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      ports:
        - containerPort: 4000
          name: http
          protocol: TCP
      env:
        - name: PORT
          value: "5000"
      livenessProbe:
        httpGet:
          path: /health
          port: 4000
        initialDelaySeconds: 20
        timeoutSeconds: 1 # no durar la prueba mas de un segundo
        periodSeconds: 15 # El periodo de tiempo
        failureThreshold: 3
