version: '3.8'

services:
  postgres:
    container_name: postgresMusic
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345root
      POSTGRES_DB: testMusic
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  app:
    build: .
    container_name: MusicApp
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: npm run dev
    ports:
      - '4000:4000'
      - '5555:5555'
    depends_on:
      - postgresMusic
    restart: always
